### ISSUE TITLE
Text of e-mail is nog extracted in the message.txt

### ISSUE THREAD

**Issue by edwinstauthamer** [TeamMsgExtractor/msg-extractor#210] opened 2021-09-06 13:02 UTC
**Bug Metadata**
* Version of extract_msg: [0.29.7]
* Your python version: Python [3.9.6]
* How did you launch extract_msg?
  - [X] My command line or
  - [ ] I used the extract_msg package

**Describe the bug**
Text from attached message is not extracted.
[testmail met  mail zonder bijlagen in mail met bijlagen.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/7116113/testmail.met.mail.zonder.bijlagen.in.mail.met.bijlagen.zip)

The attached ZIP contains a MSG-file. That MSG contains several e-mails as attachments.
The text of all those e-mails is not present in the message.txt.

Is there a message.msg file you want to share to help us reproduce this?
- [X] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
[Put your traceback here]
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfDestruction** [comment] 2021-09-06 13:11
Not a bug: message.txt is that plain text body. All of the embedded msg files are completely missing that stream, which is why they don't show up.

**Comment by edwinstauthamer** [comment] 2021-09-06 14:23
OK, so, that I understand it, we ALWAYS have to extract/dump the RTF and HTML body in a separate file, next to the message.txt. 
The message.txt always contains the header (FROM, TO etc.) and the text body if the body is in txt-format.
If the e-mail body is RTF, then the message.txt only contains the headers and the rtf-file the body.
If the e-mail body is HTML, then the message.txt only contains the headers and the html-file the body.

**Comment by TheElementalOfDestruction** [comment] 2021-09-06 23:20
For the moment, yes, although I'm the future the header will be apart of whatever message file you have, whether it be message.txt, message.rtf, or message.html.

**Comment by deepakdalakoti** [comment] 2021-11-01 05:02
Hi, Has there been any progress on this? Also I can see that the option to save message in HTML format has been commented out.

**Comment by TheElementalOfDestruction** [comment] 2021-11-01 05:10
@deepakdalakoti I'm actually not sure why this is still open, as it was not a bug, so I'm not sure what you are asking has been worked on. You can see the current progress of the module in the next-release branch where work is occurring. Version 0.29.0 is still missing a few features that are required for it to be finished (they are not easy to implement) and so is taking longer than hoped. As for saving in any format aside from txt or json, none of them have been finished yet as they require injection of the header to be considered working.

I'm closing this issue for the time being, so you can either contact me further on the discord (listed in the readme) or find the relevant issue and comment on that.

**Closed by TheElementalOfDestruction** 2021-11-01 05:10 UTC
