### ISSUE TITLE
Cant seem to get htmlBody for any .msg file

### ISSUE THREAD

**Issue by devgio** [TeamMsgExtractor/msg-extractor#137] opened 2020-07-31 11:35 UTC
I'm trying to extract the html body from different .msg files (all Outlook Message Format - Unicode) but all of them just return None for the htmlBody.

How can I save the messages so that they do have an html body?

Thanks!

**Comment by TheElementalOfCreation** [comment] 2020-07-31 19:38
Potential  duplicate of #108

**Comment by TheElementalOfCreation** [comment] 2020-07-31 19:47
The reason some msg files don't have html body's is actually usually caused by settings of the email client that sent the messages. As such, there is usually nothing you can do except make sure the messages you send do have them.

To do this, open Outlook and go to Options. The go to Mail and set "compose messages in this format" to "HTML". That should make it so any messages you send end up having an html body that can easily be used. This won't fix any messages you receive, unfortunately.

**Comment by devgio** [comment] 2020-08-03 08:19
> The reason some msg files don't have html body's is actually usually caused by settings of the email client that sent the messages. As such, there is usually nothing you can do except make sure the messages you send do have them.
> 
> To do this, open Outlook and go to Options. The go to Mail and set "compose messages in this format" to "HTML". That should make it so any messages you send end up having an html body that can easily be used. This won't fix any messages you receive, unfortunately.

Hi, thanks for your response. I tried changing that setting in outlook (it was already in HTML) and I'm still having the same issue. I even checked the Format Text tab to make sure that HTML is selected, but nothing...

What I'm doing is: I create a new email and then save it as .msg without sending it. Not sure if that makes a difference in the way the file is generated.

Please let me know if there's something else I could try.. Thanks!

**Comment by TheElementalOfCreation** [comment] 2020-08-03 08:23
There is a small possibility that you may have to actually send the email or the html to be generated. While on the surface it seems unlikely, I wouldn't rule it out. If that doesn't work, I have no more ideas and would recommend you try to contact Microsoft about it or ask on the Microsoft forums. I unfortunately have no documentation for how Outlook specifically generates msg files, only documentation on the files themselves.

**Closed** 2022-01-14 06:50 UTC
