### ISSUE TITLE
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Post". It is recommended you report this to the developers.

### ISSUE THREAD

**Issue by brooney-som** [TeamMsgExtractor/msg-extractor#206] opened 2021-08-22 17:39 UTC
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [x.x.x]
* Your python version: Python [2.7 | 3.6.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [ ] I used the extract_msg package
  - [ 

**Describe the bug**
I am reading .msg file and importing them into gmail. When I encounter a msg with a IPM.post tag I get this error:
Traceback (most recent call last):
  File "/Users/bill.rooney/git/SOM-Enterprise/brooney-softeng-som-filer/bulk_import.py", line 156, in extract_msg_file
    msg = extract_msg.openMsg(msg_path)
  File "/Users/bill.rooney/git/SOM-Enterprise/brooney-softeng-som-filer/.venv/lib/python3.8/site-packages/extract_msg/utils.py", line 384, in openMsg
    raise UnrecognizedMSGTypeError('Could not recognize msg class type "{}". It is recommended you report this to the developers.'.format(msg.classType))
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Post". It is recommended you report this to the developers.
ERROR: Could not recognize msg class type "IPM.Post". It is recommended you report this to the developers. "/Users/bill.rooney/bulk-email-test-data/Email/2015-07/2015-07-24-1137-55-GIQO x7T Newforma Automated File Items R.msg"

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
def extract_msg_file(msg_path) -> EmailMessage:
    message = EmailMessage()
    try:
        msg = extract_msg.openMsg(msg_path) # Error happens here.
    except UnrecognizedMSGTypeError as e:
        error = e   # 'can not open message file'
        print_extract_error(error, msg_path)
        return message, error

    # if not msg.messageId:
    #     error = 'MessageId not found'
    #     print_extract_error(error, msg_path)
    #     return message, error

    message['MessageId'] = msg.messageId
    message['To'] = msg.to
    message['From'] = msg.sender.replace('\r\n\t', ' ')
    message['Subject'] = msg.subject
    for header, value in msg.headerDict.items():
        value = value.replace('\r\n', '')
        if header not in message:
            message.add_header(header, value)

    message, error = set_email_message_body_from_file(msg, message)

    return message, error```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
[Put your traceback here]
```
Traceback (most recent call last):
  File "/Users/bill.rooney/git/SOM-Enterprise/brooney-softeng-som-filer/bulk_import.py", line 156, in extract_msg_file
    msg = extract_msg.openMsg(msg_path)
  File "/Users/bill.rooney/git/SOM-Enterprise/brooney-softeng-som-filer/.venv/lib/python3.8/site-packages/extract_msg/utils.py", line 384, in openMsg
    raise UnrecognizedMSGTypeError('Could not recognize msg class type "{}". It is recommended you report this to the developers.'.format(msg.classType))
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Post". It is recommended you report this to the developers.
ERROR: Could not recognize msg class type "IPM.Post". It is recommended you report this to the developers. "/Users/bill.rooney/bulk-email-test-data/Email/2015-07/2015-07-24-1137-55-GIQO x7T Newforma Automated File Items R.msg"

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfDestruction** [comment] 2021-08-22 21:59
Not actually a *bug* but honestly the error reported there is not worded the best (because even though it's my first language, I'm not great with English when it comes to documenting things). This error means the current version has no support for that type of msg file at this time, and so it can't open it. I think I remember a mention of the post type in the docs somewhere but I'm not sure exactly what kind of file that makes it. 

Anyways, unless that's just some rare way to identify one of the currently implemented MSG file types, that won't be implemented for a little while unfortunately. It will have to be added after 0.30.0.

**Comment by TheElementalOfDestruction** [comment] 2021-08-22 22:21
Confirmed, IPM.Post is a Post item (not actually sure what that is yet) which has no current support from the module.

**Comment by TheElementalOfDestruction** [comment] 2022-06-18 04:57
Turns out IPM.Post is an extremely simple format compared to a lot of the others, and is nearly identical to Message. A few tweaks to message to make it a bit neater, shift some things around, and not only will Post be implemented, but it should also be saveable, making it the third type to be saveable. I'm working on it for the next version right now.

**Comment by TheElementalOfDestruction** [comment] 2022-07-11 21:27
Completed in 0.35.0. Let me know if you have any issues with it.

**Closed by TheElementalOfDestruction** 2022-07-11 21:27 UTC
Labels: enhancement, Complete
