### ISSUE TITLE
Multiple errors trying to read attachment

### ISSUE THREAD

**Issue by andreynovikov** [TeamMsgExtractor/msg-extractor#208] opened 2021-08-30 13:50 UTC
**Bug Metadata**
* Version of extract_msg: 0.28.7
* Your python version: Python 3.7
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
I have created a mail template in Outlook 2016 and saved it as .msg file. If I add an embedded image in it accessing attachments produces multiple errors but still works.

```
    mail_template = extract_msg.openMsg('template.msg', delayAttachments=True)
    for template_attachment in mail_template.attachments:
        print(template_attachment.longFilename)
```

I will send you a msg file if you will not be able to reproduce the bug.

**Traceback**
```
ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "...\Python37\lib\site-packages\extract_msg\message_base.py", line 142, in attachments
    return self._attachments
AttributeError: 'Message' object has no attribute '_attachments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\Python37\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "...\Python37\lib\site-packages\extract_msg\utils.py", line 155, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
ERROR - Timestamp value of 79870665600.0 caused an exception. This was probably caused by the time stamp being too far in the future.
ERROR - b'@\x00\xfb\x7f\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "...\Python37\lib\site-packages\extract_msg\message_base.py", line 142, in attachments
    return self._attachments
AttributeError: 'Message' object has no attribute '_attachments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\Python37\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "...\Python37\lib\site-packages\extract_msg\utils.py", line 155, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
ERROR - Timestamp value of 79870665600.0 caused an exception. This was probably caused by the time stamp being too far in the future.
ERROR - b'@\x00\xfc\x7f\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
```

**Comment by TheElementalOfDestruction** [comment] 2021-08-30 19:13
Duplicate of #207

**Closed by TheElementalOfDestruction** 2021-08-30 19:13 UTC
