### ISSUE TITLE
Change in support for RTF/HTML?

### ISSUE THREAD

**Issue by mtdukes** [TeamMsgExtractor/msg-extractor#183] opened 2021-02-14 19:49 UTC
I'm looking to integrate this library into a msg/eml parser, and it looks like there may have been a change in how `extract_msg.Message.save` handles rtf and html within a message body. Is there currently a way to extract html/rtf from a msg file (if it exists) in this library?

Thanks in advance and sorry if I missed something in my review of existing closed/open issues.

**Comment by TheElementalOfDestruction** [comment] 2021-02-14 21:41
Currently, unless the msg file directly provides those streams, we don't support extracting them. As for the save function, I actually meant to leave those parameters commented out so that the framework would remain but would be unusable. Currently there is no support for those types (as I still need to determine how the module should make decisions about what to do when it can't find a stream) but it is planned for the near future. I also have to write the code that would generate the to, from, cc, subject, etc. fields in either html or rtf which is a bit of a pain.

Also planned is the adding of a system that can deencapsulate html tags from an RTF stream. If your message has an RTF body, chances are that there is html inside of it. See https://github.com/TeamMsgExtractor/msg-extractor/issues/137 for more information.

**Comment by mtdukes** [comment] 2021-02-14 21:45
Thanks for the quick response. It does look like my test examples are missing `htmlBody` but contain `rtfBody`. So at least I'm able to extract that info, which I might be able to use to write to a file.

**Comment by edwinstauthamer** [comment] 2021-07-23 15:48
Hi, Is there any progress on the implementation for extracting the message body as HTML or RTF?

**Comment by TheElementalOfDestruction** [comment] 2021-07-23 15:53
If you need the bodies themselves (and not the header with to, from, etc. then there are properties to access them directly. However the next version of msg-extractor will have support for saving the message as rtf or html (depending on available data). Development is taking a bit because I want to do it right and not half ass it like I've done in personal code. Aside from that, most of the code for the next version is actually done.

**Comment by edwinstauthamer** [comment] 2021-07-24 14:30
OK I really need this functionality. When will the new version be released? I would gladly take a bèta version to try it out.

**Comment by TheElementalOfDestruction** [comment] 2021-07-24 18:16
In the new version they are currently just a pass statement as this point as I figure out how to actually do them. Doing them requires investigating thoroughly the html and the etc structures that are given. There is no beta for the features at this time. 

Technically this entire module is considered (at least by myself) to be a beta version (all of it is marked as pre-release) as we have yet to have a 1.0.0 release. However the next version does have a preview (with the html and rtf still pass statements) which I made mentioned on the Discord. It's in a public repository (which will eventually be completely merged into this repository for easy access) so you can download it and test for errors.

If you want to help with testing these features while I try to implement it, I would very much appreciate it. Currently I am limited to testing on my own private collection of .msg files and would love to either have direct access to many more or would be satisfied with indirect access through a tester. If you let me know through the Discord that would be the easiest method as we can discuss times and easily message back and forth and new commits and do tests much faster. If you are interested in that, the Discord is in the readme.

Finally, if all you need is the body and not the header, you can access the found streams for these through the following properties: `Message.htmlBody`, `Message.rtfBody`, and `Message.body` for the plain text body.

Thank you, and have a wonderful day.

**Comment by edwinstauthamer** [comment] 2021-07-26 10:22
Good to read that there is progress. I do understand that these things take time as this is probably a project next to your normal job.
At this time we are using the solution as a command line solution that is called from within a Powershell-script. 
Obviously we do not ask money for the use of the software. We are not using the solution in a production-environment. We are testing/seeing how well the msg_extractor works. 

I already made some changes/improvements because the original version didn't handle multiple "dots" in the file path and ran into problems with the length of the path, directory and file names. But... because one can have e-mails in e-mails in emails in...... we still run into problems when the structure is to deep.
These improvements are quick & dirty... I am not proud of my coding skills :). 
I am no Python programmer but I can read, edit and add to existing code. It would help me to now/have example code of how to write the Message.htmlBody and/or Message.rtfBody to a file, next to the txt-file that is written. Maybe you can give me a hint/example code for this?

I am testing this on a set of 17.000 msg-files in a client environment. So I cannot share the files with you. 
Currently 66 msg-files cannot be extracted in any way (so no subdir is created). 55 files give errors: partially extracted with "raw" directies. 

I you want I can give you the output of the errors and/or contents of the "raw" directories.

**Comment by TheElementalOfDestruction** [comment] 2021-07-26 11:17
Actually it's mostly school that's been keeping me busy, along side some personal stuff, lol.

For the path problem, I actually noticed that myself and made a sort of work around. Now you can directly save all the files into a zip file, which doesn't have a limit (or at least the limit is much larger) on the path length, so you don't get errors. The version with that is technically functional, although again the html and rtf just do nothing right now. You can find it here: https://github.com/TheElementalOfDestruction/msg-extractor

You specifically mention paths with multiple dots. Can you please tell me where you are entering them (what functions or through the console) and an example path that would cause problems? I'd like to make sure those problems don't exist in the new version before I push it out. The module uses some functions that are supposed to automatically convert relative paths to absolute paths (just to make things handle better internally) but it sounds like they might not be working as intended.

For both bodies, it's simply a matter of opening a file and writing to them. Here is exactly the code that would work (assuming you want to save to the current directory):
```python
import extract_msg

msg = extract_msg.openMsg('path/to/msg.msg')

# Save the html, if it exists.
if msg.htmlBody:
    with open('output.html', 'wb') as f: # Open the output file in binary write mode. "With" will automatically handle closing it.
        f.write(msg.htmlBody) # Write the data.

# Save the rtf, if it exists.
if msg.rtfBody:
    with open('output.rtf', 'wb') as f:
        f.write(msg.rtfBody)
```

As for the errors, if they are all the same then please send me a traceback for them, either here, through the discord, or by email (arceusthe@gmail.com). If any of them seem to be unique, specifically they have messages that are probably related to that specific file, then please make a note of which files and also send me the trackbacks. I may request that you run some code on them later to diagnose the issue, and it would be unfortunate if you could not remember which ones gave you the errors. 

Thank you.

**Comment by edwinstauthamer** [comment] 2021-08-02 19:24
Sorry for the delay. I am a consultant working on multiple projects so I have to divide my time :). 

I will send you the examples of issues with multiple dots and the code that I changed to handle that by mail.

This is off topic for this thread so I think that is better.

**Comment by TheElementalOfDestruction** [comment] 2022-01-14 06:51
From my tests this should all be working now so I'll be closing this issue. Some branching issues have been created for various pieces of this that are too specific to really be covered. If this main issue is still relevant, let me know.

**Closed by TheElementalOfDestruction** 2022-01-14 06:51 UTC
