### ISSUE TITLE
Error instantiating Message on Windows

### ISSUE THREAD

**Issue by micheben** [TeamMsgExtractor/msg-extractor#211] opened 2021-09-13 13:17 UTC
**Bug Metadata**
* Version of extract_msg: 0.28.7
* Your python version: Python 3.7.11 (Windows)
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**

Tried to instantiate the `Message` Class and an error occured.

```
from extract_msg.message import Message
b = open("test.msg", "rb").read()
msg = Message(path=b)
```

**Traceback**
```
Traceback (most recent call last):
  File "Z:\Platform37\lib\site-packages\extract_msg\message_base.py", line 261,
in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\Platform37\lib\site-packages\extract_msg\message_base.py", line 250,
in date
    return self._date
AttributeError: 'Message' object has no attribute '_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\Platform37\lib\site-packages\extract_msg\properties.py", line 128, in
 date
    return self.__date
AttributeError: 'Properties' object has no attribute '_Properties__date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\Platform37\lib\site-packages\extract_msg\message.py", line 29, in __i
nit__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAtt
achments, overrideEncoding, attachmentErrorBehavior)
  File "Z:\Platform37\lib\site-packages\extract_msg\message_base.py", line 53, i
n __init__
    self.header
  File "Z:\Platform37\lib\site-packages\extract_msg\message_base.py", line 270,
in header
    header.add_header('Date', self.date)
  File "Z:\Platform37\lib\site-packages\extract_msg\message_base.py", line 252,
in date
    self._date = self._prop.date
  File "Z:\Platform37\lib\site-packages\extract_msg\properties.py", line 133, in
 date
    self.__date = self.get('30080040').value.__format__('%a, %d %b %Y %H:%M:%S %
z')
ValueError: Invalid format specifier
```

**Comment by TheElementalOfDestruction** [comment] 2021-09-13 21:44
Duplicate of #169 (this is caused by an issue with your tzlocal package, not out module. See that issue for the test that will prove it)

**Closed by TheElementalOfDestruction** 2021-09-13 21:44 UTC
